name: Generate Neofetch Card
on:
  schedule:
    - cron: "0 0 * * *" # Updates your stats every day automatically!
  workflow_dispatch: # Lets you trigger it manually anytime

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: jauzin23/ReadNeo@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # You can toggle any of these modules on or off!
          ascii_path: ".github/ascii.txt"
          os: "Windows 11"
          ide: "VS Code"
          show_os: "true"
          show_uptime: "true"
          show_ide: "true"
          show_languages: "true"
          show_repos: "true"
          show_stars: "true"
          show_commits: "true"
          show_followers: "true"
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update card
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
